
services:
  db:
    image: mysql:5.6
    container_name: webcat-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webcat
      MYSQL_USER: webcat_user
      MYSQL_PASSWORD: strongpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  webcat:
    build: .
    container_name: webcat2
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: db

volumes:
  db_data:

